### numpy 공부
- 배열은 같은 종류의 데이터만 담을 수 있다.
- 배열은 차원을 갖는다.
- 배열은 빠르고 간단하게 연산을 처리할 수 있다.


In [1]:
import numpy as np

#### 배열 만들기

In [3]:
# 초기화할 값을 지정하여 배열 생성
np.array([1,2,3])

array([1, 2, 3])

In [9]:
# 값을 0으로 초기화하여 배열 생성
np.zeros(5), np.zeros((5,5))

(array([0., 0., 0., 0., 0.]),
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]))

In [11]:
# 값을 1로 초기화하여 배열 생성
np.ones(5), np.ones((5,5))

(array([1., 1., 1., 1., 1.]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [14]:
# zeros & ones ≠ empty
np.empty(5), np.empty((5,5)) # 의미 없는 값

(array([1., 1., 1., 1., 1.]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [19]:
# 수의 순차적인 증감을 이용하여 배열 생성
np.arange(10), np.arange(1,10,2)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 3, 5, 7, 9]))

In [25]:
# 랜덤함 숫자로 배열 생성
np.random.rand(5), np.random.rand(5,5)

(array([0.46777252, 0.07258082, 0.99915526, 0.00680057, 0.12301459]),
 array([[0.17890283, 0.50601885, 0.19252291, 0.38303365, 0.26926555],
        [0.58475936, 0.9437402 , 0.04109066, 0.14414063, 0.7381808 ],
        [0.06730378, 0.93410682, 0.06801989, 0.38750861, 0.33788116],
        [0.6436721 , 0.53827575, 0.14999371, 0.24880485, 0.67947475],
        [0.65690596, 0.59440333, 0.16177077, 0.61022992, 0.28381992]]))

In [27]:
# 범위 내에서 랜덤 추출
np.random.randint(1,10)

3

In [32]:
# 표준정규분포에서 랜덤 추출(표준정규분포 = 평균 : 0, 표준편차 1인 정규분포)
np.random.randn()

0.5752298144242786

In [45]:
np.random.seed(1) ; np.random.randint(1,10) # seed 번호에 값 줌
np.random.seed(1) ; np.random.randint(1,10) # seed 번호가 가진값으로 활용하는 느낌

6

In [63]:
tmp_array = np.arange(1,10) # 배열 생성
np.random.shuffle(tmp_array) # 섞음, 이때 inplace해버림
print(tmp_array) # 배열 확인

[5 1 6 8 3 4 7 9 2]


In [68]:
np.arange(16).reshape(4,4), np.arange(16).reshape(4,4).reshape(2,2,4)

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],
 
        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]]]))

In [81]:
tmp = np.arange(16).reshape(4,4).reshape(2,2,4)
tmp.shape, tmp.dtype, tmp.astype('float').dtype

((2, 2, 4), dtype('int64'), dtype('float64'))

In [90]:
np.arange(16)[15], np.arange(16)[-1], np.arange(16)[-3:-1]

(np.int64(15), np.int64(15), array([13, 14]))

In [94]:
arr = np.arange(16)
arr[-1] = 1
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,  1])

In [95]:
# 여러 값 할당
arr[6:8] = [200, 201]
arr

array([  0,   1,   2,   3,   4,   5, 200, 201,   8,   9,  10,  11,  12,
        13,  14,   1])

In [103]:
# 행, 열로 인덱싱
np.arange(16).reshape(4,4)[0][1]

# 같은 결과임
np.arange(16).reshape(4,4)[0][1], np.arange(16).reshape(4,4)[0, 1] 

(np.int64(1), np.int64(1))

In [105]:
tmp_array = np.arange(16).reshape(4,4)
tmp_array[0][1] = 100
tmp_array

tmp_array[0,2] = 100
tmp_array

array([[  0, 100, 100,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15]])

In [107]:
tmp_array[0:2, 2:4]

array([[100,   3],
       [  6,   7]])

In [108]:
tmp_array[:2, 2:]

array([[100,   3],
       [  6,   7]])

In [135]:
# score 리스트를 일일히 만들면 불편하니, 랜덤으로 10개 생성
np.random.seed(42); scores = [(np.random.randint(1,9)) * 10 for i in range(10)]

score_array = np.array(scores)
score_array >= 70

score_array[score_array >= 70] = 999
score_array

array([999,  40,  50, 999,  30, 999,  50,  50, 999,  20])

In [132]:
arr = np.arange(1,5)
arr + 5

array([6, 7, 8, 9])

In [133]:
arr * 10

array([10, 20, 30, 40])

In [142]:
arr2 = np.arange(6,10)
arr2

arr, arr2, arr + arr2

(array([1, 2, 3, 4]), array([6, 7, 8, 9]), array([ 7,  9, 11, 13]))

In [143]:
# 제곱
np.square(arr)

array([ 1,  4,  9, 16])

In [144]:
# 제곱근(루트)
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [145]:
# exp(지수승) e^1
# e = 2.718... 자연상수 / 오일러 수
np.exp(arr)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [148]:
# log
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [150]:
np.add(arr, arr2)

array([ 7,  9, 11, 13])

In [155]:
# 요소의 합
arr, np.sum(arr)

(array([1, 2, 3, 4]), np.int64(10))

In [157]:
# 누적 합계
arr, np.cumsum(arr)

(array([1, 2, 3, 4]), array([ 1,  3,  6, 10]))

In [158]:
# 요소 평균
np.mean(arr)

np.float64(2.5)

In [159]:
# 편차
np.var(arr)

np.float64(1.25)

In [160]:
# 표준편차
np.std(arr)

np.float64(1.118033988749895)

In [161]:
# 최소값
np.min(arr)

np.int64(1)

In [162]:
np.max(arr)

np.int64(4)

In [164]:
# 최소값의 인덱스
np.argmin(arr)

np.int64(0)

In [166]:
# 최대값의 인덱스
np.argmax(arr)

np.int64(3)

In [170]:
arr = np.arange(10).reshape(2,5)
arr, arr.transpose(), arr.T # 축 지정 안하면 이렇게도 가능

(array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[0, 5],
        [1, 6],
        [2, 7],
        [3, 8],
        [4, 9]]),
 array([[0, 5],
        [1, 6],
        [2, 7],
        [3, 8],
        [4, 9]]))

In [178]:
# 3차원 축배열
arr3d = np.arange(27).reshape(3,3,3)
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [188]:
arr3d.transpose(0,1,2),\
arr3d.transpose(0,2,1),\
arr3d.transpose(1,0,2),\
arr3d.transpose(1,2,0),\
arr3d.transpose(2,0,1),\
arr3d.transpose(2,1,0) # 인수 생략 가능

(array([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],
 
        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],
 
        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]]),
 array([[[ 0,  3,  6],
         [ 1,  4,  7],
         [ 2,  5,  8]],
 
        [[ 9, 12, 15],
         [10, 13, 16],
         [11, 14, 17]],
 
        [[18, 21, 24],
         [19, 22, 25],
         [20, 23, 26]]]),
 array([[[ 0,  1,  2],
         [ 9, 10, 11],
         [18, 19, 20]],
 
        [[ 3,  4,  5],
         [12, 13, 14],
         [21, 22, 23]],
 
        [[ 6,  7,  8],
         [15, 16, 17],
         [24, 25, 26]]]),
 array([[[ 0,  9, 18],
         [ 1, 10, 19],
         [ 2, 11, 20]],
 
        [[ 3, 12, 21],
         [ 4, 13, 22],
         [ 5, 14, 23]],
 
        [[ 6, 15, 24],
         [ 7, 16, 25],
         [ 8, 17, 26]]]),
 array([[[ 0,  3,  6],
         [ 9, 12, 15],
         [18, 21, 24]],
 
        [[ 1,  4,  7],
         [10, 13, 16],
         [19, 22, 

In [217]:
arr = np.arange(10).reshape(2,5)
np.save('dump/array', arr) # 제목 + .npy로 저장됨

In [218]:
load_arr =  np.load('dump/array.npy')
load_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [214]:
# 여러 개의 배열은 npz로 저장됨
np.savez('dump/compressed_array', array1 = arr, test= load_arr)

In [215]:
tmp_arr = np.load('dump/compressed_array.npz')
tmp_arr['array1'], tmp_arr['test']

(array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]))